[package]
name = "cable-streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "3.1"
serde = { version = "1.0", features = [ "derive" ] }
quick-xml = { version = "0.22", features = [ "serialize" ] }
